version: 2.1

orbs:
  docker: circleci/docker@2.1.3
  go: circleci/go@1.7.1

parameters:
  kustomize-version:
    type: string
    default: v4.5.7

jobs:
  build:
    docker:
     - image: cimg/base:2022.08
    steps:
      - go/install:
          version: "1.17"
      - run:
          name: "Install kustomize"
          command: |
            URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/<< pipeline.parameters.kustomize-version >>/kustomize_<< pipeline.parameters.kustomize-version >>_linux_amd64.tar.gz
            curl -L $URL | tar zx

            [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo
            $SUDO chmod +x ./kustomize
            $SUDO mv ./kustomize /usr/local/bin
      - docker/install-docker
      - checkout
      - run: ./domino-build.sh
