#!/bin/bash

# Source: https://www.rabbitmq.com/kubernetes/operator/install-operator.html

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo ">>> Creating namespaces..."
kubectl create namespace rabbitmq-system
kubectl create namespace rabbitmq

echo ">>> Installing cert-manager (required for Messaging Topology Operator)..."
kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
kubectl label namespace cert-manager cert-manager.io/disable-validation=true --overwrite=true || true
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
kubectl wait --for=condition=Available deployments --all --timeout 120s -n cert-manager || true

echo ">>> Installing rabbitmq cluster operator..."
kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/download/v2.17.2/cluster-operator.yml"

echo ">>> Installing rabbitmq messaging topology operator..."
kubectl apply -f "https://github.com/rabbitmq/messaging-topology-operator/releases/download/v2.16.0/messaging-topology-operator-with-certmanager.yaml"

sleep 5

echo ">>> wait for rabbitmq operators"
kubectl wait --for=condition=Available deployments --all --timeout 120s -n rabbitmq-system

echo ">>> Creating rabbitmq cluster..."
kubectl apply -f "${SCRIPT_DIR}/manifests/rabbitmq/rabbitmq-cluster.yaml" || true

sleep 5 # not a great solution for things not being ready for the next step

echo ">>> Waiting for RabbitMQ cluster to become ready..."
kubectl wait RabbitMQCluster/rabbitmq-cluster --for=condition=ALLREPLICASREADY --timeout=300s -n rabbitmq

echo ">>> Creating seldon rabbitmq user..."
kubectl apply -f "${SCRIPT_DIR}/manifests/rabbitmq/seldon-rabbitmq-user.yaml"
