#!/bin/bash

# Source: https://www.rabbitmq.com/kubernetes/operator/install-operator.html

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo ">>> Creating namespaces..."
kubectl create namespace rabbitmq-system
kubectl create namespace rabbitmq


echo ">>> Installing rabbitmq operator..."
kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/download/v2.17.2/cluster-operator.yml"

sleep 5

echo ">>> wait for rabbitmq operator"
kubectl wait --for=condition=Available deployments --all --timeout 120s -n rabbitmq-system

echo ">>> Creating rabbitmq cluster..."
kubectl apply -f "${SCRIPT_DIR}/manifests/rabbitmq/rabbitmq-cluster.yaml" || true

sleep 5 # not a great solution for things not being ready for the next step

echo ">>> Waiting for RabbitMQ cluster to become ready..."
kubectl wait RabbitMQCluster/rabbitmq-cluster --for=condition=ALLREPLICASREADY --timeout=300s -n rabbitmq

echo ">>> Creating seldon rabbitmq user..."
kubectl apply -f "${SCRIPT_DIR}/manifests/rabbitmq/seldon-rabbitmq-user.yaml"
