#!/bin/bash

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo ">>> Deleting seldon rabbitmq user..."
kubectl delete -f "${SCRIPT_DIR}/manifests/rabbitmq/seldon-rabbitmq-user.yaml" --ignore-not-found=true || true

echo ">>> Deleting rabbitmq cluster..."
kubectl delete -f "${SCRIPT_DIR}/manifests/rabbitmq/rabbitmq-cluster.yaml" --ignore-not-found=true || true

echo ">>> Uninstalling rabbitmq messaging topology operator..."
kubectl delete -f "https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.6.0/messaging-topology-operator-with-certmanager.yaml" --ignore-not-found=true || true

echo ">>> Uninstalling rabbitmq cluster operator..."
kubectl delete -f "https://github.com/rabbitmq/cluster-operator/releases/download/v2.17.2/cluster-operator.yml" --ignore-not-found=true || true

echo ">>> Deleting namespaces..."
kubectl delete namespace rabbitmq --ignore-not-found=true
kubectl delete namespace rabbitmq-system --ignore-not-found=true

echo ">>> Done removing rabbitmq."
