#!/bin/bash

# Create RabbitMQ models using rabbitmq-ha chart approach
# Note: Queues should already be created by install-rabbitmq-ha script

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

MODELS_DIR=$SCRIPT_DIR/../../models

COMPUTE_NAMESPACE=seldon-regression-test

echo ">>> Creating iris rabbitmq model..."
kubectl apply -f $MODELS_DIR/iris-model-rabbitmq-ha.yaml -n $COMPUTE_NAMESPACE

sleep 5

echo ">>> Waiting for iris model deployment to become available..."
kubectl wait deployment.apps/iris-model-rabbitmq-default-0-classifier -n $COMPUTE_NAMESPACE --for condition=Available=True --timeout=600s

echo ">>> Done deploying models."
