#!/bin/bash

# Delete RabbitMQ models using rabbitmq-ha chart approach

set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

MODELS_DIR=$SCRIPT_DIR/../../models

COMPUTE_NAMESPACE=seldon-regression-test

echo ">>> Deleting iris rabbitmq model..."
kubectl delete -f $MODELS_DIR/iris-model-rabbitmq-ha.yaml -n $COMPUTE_NAMESPACE --ignore-not-found=true || true

echo ">>> Done deleting models."

