name: V1 Operator Tests

on:
  push:
    branches: [ master, rabbitmq* ]
  pull_request:
    branches: [ master, rabbitmq*  ]

jobs:
  operator-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.25.13'
    - name: test-operator
      env:
        GOTOOLCHAIN: go1.25.13
      run: |
        make -C operator test
